### ISSUE TITLE
Transcripts Metadata

### ISSUE THREAD

**Issue by alfonsocanuk** [susanssky/careless-whisper#11]
We will add Metadata capabilities to our transcripts

**Comment by susanssky** [comment]
@alfonsocanuk I guess it refer backend(+database)..?

**Comment by alfonsocanuk** [comment]
Yes. When performing searches of transcripts are we only doing text search or are we also searching by other criteria like keywords, categories, speaker, participantes, duration, etc. This story is to create those capabilities. If we decide add these options in the search, we need to add these in the database, and post create and update.
