### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by alfonsocanuk** [susanssky/careless-whisper#12]
#67  Add voting capabilities to transcripts

- Database tables to hold voting info
- User should be able to vote (should be able to hit "like" and"unlike") 
- Users need to be authenticated and can only vote once per transcript.

**Comment by susanssky** [comment]
voting isn't need, please change number of views

**Comment by leilafarsani** [comment]
I am thinking to do the last part as a functionality inside the app and make an error handler for that.  I think it could be added in issue 25.  Please let me know what do you think? Thanks

**Comment by susanssky** [comment]
@leilafarsani you can put one to belong 'frontend', and another one belongs 'backend'.....(?)
