### ISSUE TITLE
Load Transcripts (authenticated user)

### ISSUE THREAD

**Issue by alfonsocanuk** [susanssky/careless-whisper#22]
This task is to make sure that now the information being displayed (work done in issue #10) can only be seen if the user has been authenticated. I a non authenticated user navigates to the browse transcripts page, there should show nothing and display a message like "Please login to see transcripts".

**Comment by susanssky** [comment]
I moved the display page to the dashboard directory... so I think it won't display the msg like "Please login to see transcription"
