### ISSUE TITLE
Database Connector

### ISSUE THREAD

**Issue by alfonsocanuk** [susanssky/careless-whisper#4]
Create a database connector which will be used by the application to access the Database

AC:
Able to open connections to the database and perform CRUD operations.

**Comment by susanssky** [comment]
I would like to clarify if the database connector provides the database URL. If so, then this falls under the category of "cannot be proven through a PR". Generally, in local projects on computers or laptops, we save confidential data, including the database URL, in an .env file. We do not publicly disclose the database URL in a GitHub repository, as this could pose a security risk and potentially lead to a database breach. Therefore, the .env file is automatically skipped when uploading to GitHub.

I hope I have not misunderstood anything. Please let me know if you have any questions. If I have understood correctly, the contents of this issue may need to be rewritten for another purpose.

**Comment by alfonsocanuk** [comment]
This is for the code you need to write to open a connection to the DB. The idea is that you do not repeat the code to open a DB connection and send queries everywhere where you need to query the DB. Instead, you have this code in a single file and you call this new function from other places in the code. This is important so in the event you have to change the database to something else like MD Sql Server, you only need to change the connector code. Making your code DB agnostic when possible is a good practice.

**Comment by susanssky** [comment]
Thank you for providing additional clarification.

### To any developer who wants to pick up this issue: 
>use the code from ./db

https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices
