### ISSUE TITLE
Upload example transcripts to Database

### ISSUE THREAD

**Issue by alfonsocanuk** [susanssky/careless-whisper#5]
#26 

AC:
Database should have a few records with example transcripts to be used by the app.

**Comment by susanssky** [comment]
This seems somewhat similar to issue #15... could you clarify how the two differ, please? Thank you.
If there are no differences, should be rewritten this issue with another "target"?

**Comment by alfonsocanuk** [comment]
This issue is for populating the database with test data. The other one is to actually build the functionality to give users the ability to upload transcripts.  The idea is that you can start working on other features like browse and search transcripts before you have completed the Upload feature.

**Comment by susanssky** [comment]
Thank you for providing additional clarification.
### To any developer who wants to pick up this issue. 
Providing false data to verify whether it has been uploaded to the database.
https://www.prisma.io/docs/guides/migrate/seed-database#user-defined-arguments
>see the code from seed.ts

#15:
```ts
export async function POST(request: Request) {
  const body: Body = await request.json();
  const user = await prisma.user.create({
    data: body,
  });
  return new Response(JSON.stringify(user));
}
```
