### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by alfonsocanuk** [susanssky/careless-whisper#6]
Propose a UI design which will help define Database tables. No coding required, only a vision of what the app will look like and what behaviours will support. What would be the different user journeys.

**Comment by susanssky** [comment]
<img width="910" alt="螢幕截圖 2023-06-23 09 10 20" src="https://github.com/susanssky/careless-whisper/assets/107769663/8de8e837-cf28-404a-b70f-64149a1f2bc7">

If there are any questions, please feel free to let me know, thank you

**Comment by alfonsocanuk** [comment]
Please look at this web: https://www.smartdraw.com/flowchart/flowchart-symbols.htm

Try to use the right shapes and also please add the interactions with the database (writes with an arrow pointing to the database shape. reads with arrows coming out of the database shape).

Example:
![Image](https://github.com/susanssky/careless-whisper/assets/136838749/5065f6ca-a67f-48f1-a765-741a66505c0f)

**Comment by susanssky** [comment]
Since the SmartDraw does not have as much freedom as Miro, I continue to use MIRO...
<img width="1218" alt="螢幕截圖 2023-06-23 12 13 54" src="https://github.com/susanssky/careless-whisper/assets/107769663/a2718fc1-f849-4d86-aa27-ecf24dc9014a">
