### ISSUE TITLE
Cancelling the vote

### ISSUE THREAD

**Issue by leilafarsani** [susanssky/careless-whisper#68]
- adding cancel vote button
- When the button clicks the voted button will be cancelled and will be activated for vote.
- When the button clicks the voted the number of votes should decrement.

**Comment by susanssky** [comment]
Actually, I would prefer to have a feature that allows users to "cancel their vote"... because sometimes users accidentally press the wrong vote button, either upvote or downvote, and can't undo it. What can be done in this situation?

**Comment by leilafarsani** [comment]
Yes, I agree with you. @susanssky 

Do you think we need a separate button for that?!
I am open for ideas and also thinking about the best approach to do that!

**Comment by susanssky** [comment]
At the moment, only one is sufficient. As for the downvote button, I don't think it's absolutely necessary and it could potentially discourage mentors.(?)

**Comment by leilafarsani** [comment]
Yeah, maybe 
Maybe input for feedback is better than downvote?!

**Comment by susanssky** [comment]
Yes but I hope at least you have done the 'edit the transcript'. I know its priority is low but I hope it can has full CRUD in the app..

**Comment by leilafarsani** [comment]
Yes, I did the backend part already 
and will finalize it ASAP.This issue is not for now, that is why it is still in the backlog 
So don't worry about it
